# docker-compose.yml (u test_api repo-u - SA LABELAMA)
services:
  test-api:
    image: test-api:dev
    container_name: test-api
    restart: unless-stopped
    ports:
      # HOST_PORT:CONTAINER_PORT
      - "3001:5000" # Proveri da li je interni port 5000 i dalje tačan
    labels:
      # --- Traefik Konfiguracija ---
      - "traefik.enable=true" # Govori Traefiku da koristi ovaj kontejner

      # --- HTTPS Ruter ---
      # Ime rutera mora biti jedinstveno, @dockerRemote označava da dolazi od tog providera
      - "traefik.http.routers.test-api-auto.rule=Host(`test-api.m-t.dev`)"
      - "traefik.http.routers.test-api-auto.entrypoints=websecure"
      - "traefik.http.routers.test-api-auto.service=test-api-auto-svc"
      - "traefik.http.routers.test-api-auto.tls=true" # Eksplicitno kažemo da koristi TLS
      - "traefik.http.routers.test-api-auto.tls.certresolver=letsencrypt" # Koristi LE resolver

      # --- Traefik Servis ---
      # VAŽNO: server.port mora biti HOST_PORT iz 'ports' sekcije (3001)!
      - "traefik.http.services.test-api-auto-svc.loadbalancer.server.port=3001"
      # Shema aplikacije unutar kontejnera
      - "traefik.http.services.test-api-auto-svc.loadbalancer.server.scheme=http"