# docker-compose.yml (u test_api repo-u - BEZ LABELA)
services:
  test-api:
    image: test-api:dev
    container_name: test-api
    restart: unless-stopped
    ports:
      - "3001:5000" # HOST_PORT:CONTAINER_PORT
    # Obrisana labels: sekcija