apiVersion: v1
kind: Service
metadata:
  name: test-api
  namespace: test-api
  labels:
    app: test-api
spec:
  selector:
    app: test-api
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 